### ISSUE TITLE
1.20.1 port?

### ISSUE THREAD

**Issue by VeggeieDude** [StickyPiston-development/BuildersJetpack#1]
Heya! This mod looks super cool! Was wondering if you'd be willing to port it to 1.20.1

If not np, ty!

**Comment by MrStickyPiston** [comment]
Thank you for submitting an issue, i think i will be porting it soon, but i dont know how many time it will take. Sorry for the late response.

**Comment by MrStickyPiston** [comment]
@VeggeieDude it appears that the config library has not been ported yet, i have to wait before they update.

**Comment by remd** [comment]
@MrStickyPiston Are you referring to https://github.com/Toma1O6/Configuration?

It looks like it has been updated for 1.20 as well as 1.21. It would be awesome to see your mod updated for latest Minecraft. It's a great jetpack for Survival.

**Comment by MrStickyPiston** [comment]
Thank you, i will port it soon.

**Comment by MrStickyPiston** [comment]
https://modrinth.com/mod/builders-jetpack/version/xTKwa6ZA
still working on 1.21

**Comment by MrStickyPiston** [comment]
1.21 is there: https://modrinth.com/mod/builders-jetpack/version/KQaX3osi
it is still beta, so please open a new issue if you find a bug!
