### ISSUE TITLE
Kibe utilities compat

### ISSUE THREAD

**Issue by LuckyDog322** [StickyPiston-development/BuildersJetpack#2]
![2024-07-19_16 07 46](https://github.com/user-attachments/assets/92106b00-947a-4306-beff-d522e88387e3)
double tap space invalid

**Comment by MrStickyPiston** [comment]
Can i see your keybinds settings?

**Comment by LuckyDog322** [comment]
ok

**Comment by MrStickyPiston** [comment]
Also, do you have any other mods?

**Comment by LuckyDog322** [comment]
![QQ截图20240720150150](https://github.com/user-attachments/assets/173cf7cc-43a0-4059-858b-f44a1317356d)
![QQ截图20240720150158](https://github.com/user-attachments/assets/af683d88-f186-4bf9-811b-15726fbb1cea)
![QQ截图20240720150205](https://github.com/user-attachments/assets/e2022589-7a32-4b5f-95b4-07aa2d223a38)
![QQ截图20240720150215](https://github.com/user-attachments/assets/d9ca82d1-c5dc-45c3-89d7-237f05630341)
![QQ截图20240720150222](https://github.com/user-attachments/assets/453cac6c-e14c-4b19-812d-0805114fb352)
![QQ截图20240720150228](https://github.com/user-attachments/assets/f47188a8-6df5-4307-8831-d4f97f70307f)
![QQ截图20240720150236](https://github.com/user-attachments/assets/ee9f336b-ab61-4c50-9239-7a65dd19b321)
![QQ截图20240720150243](https://github.com/user-attachments/assets/722dd4fe-72dc-42e2-943a-f1a5646acf1c)
![QQ截图20240720150256](https://github.com/user-attachments/assets/d170b547-40b7-4aa0-afa9-f20716733917)
![QQ截图20240720150301](https://github.com/user-attachments/assets/f87a228f-16e3-41f9-8128-f5536c16a6c6)
![QQ截图20240720150307](https://github.com/user-attachments/assets/738c6eea-8016-47f6-ae3f-444f610d77dc)

**Comment by MrStickyPiston** [comment]
Try pressing the jump button twice shortly after eachother. Im sorry that i cant understand your language.

**Comment by LuckyDog322** [comment]
ok, I have identified an issue, it is caused by a tool called Kibe Utilities mod

**Comment by LuckyDog322** [comment]
![Uploading 1.png…]()

**Comment by MrStickyPiston** [comment]
The image has not uploaded yet.

**Comment by LuckyDog322** [comment]
![1](https://github.com/user-attachments/assets/f3e4bce0-e460-4c3c-9006-85e1aa09b245)

**Comment by MrStickyPiston** [comment]
I think it is an issue with the angel ring.

**Comment by MrStickyPiston** [comment]
I think it is an issue with the angel ring.

**Comment by LuckyDog322** [comment]
You think there's a conflict?

**Comment by LuckyDog322** [comment]
It's still a compatibility issue

**Comment by LuckyDog322** [comment]
hi， I have discovered another conflict mod
![屏幕截图 2024-09-23 163107](https://github.com/user-attachments/assets/65d09f65-20db-4818-88e4-535e2a1d55b8)

**Comment by MrStickyPiston** [comment]
Could you send logs, behaviour and the mod link?

**Comment by LuckyDog322** [comment]
His situation is the same as last time. After installation, the backpack cannot fly, but after uninstallation, it returns to normal

**Comment by MrStickyPiston** [comment]
Im sorry, but this issue is hard to solve and as these problems are compatibility problems they dont affect as many people as other issues and i dont have all time of the world, so im not going to fix this issue.

I hope you can find another mod as replacement to this mod or the other mods.
