### ISSUE TITLE
Please update to 1.21.1

### ISSUE THREAD

**Issue by flyover0112** [StickyPiston-development/BuildersJetpack#3]
Please update to 1.21.1, thank you in advance.

**Comment by MrStickyPiston** [comment]
Please make a separate issue for enchanting. I tried before and it did not work but i hope i can get it working now

**Comment by flyover0112** [comment]
I already did, and what with an update to 1.21.1?

**Comment by MrStickyPiston** [comment]
done, https://modrinth.com/mod/builders-jetpack/version/1.4.6
