### ISSUE TITLE
Update 1.4.5 - 1.21.1 Not Working with Sinytra Connector

### ISSUE THREAD

**Issue by flyover0112** [StickyPiston-development/BuildersJetpack#5]
I'm trying to use this mod on 1.21.1 Neoforge with Sinytra connector (a mod that makes it possible to run Fabric mods on Forge/Neoforge), usually, all FABRIC mods work with no problem.
In this case, I am getting the message that the mod is still for the 1.21 version, maybe there is some other place to change the MC version to be compatible. Please can you look into that and fix it? Love your mod so much and it is hard to live without it. Thank you very much. 
Here is a paste of the MC log: 

Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
   - Replace mod Minecraft (Minecraft) 1.21.1 with version 1.21.
More details:
   - mod Builders Jetpack (builders_jetpack) 1.4.5 requires version 1.21 of mod Minecraft (Minecraft), but only the wrong version is present: 1.21.1!
   - mod Configuration (configuration) 2.3.0 requires version 1.21 of mod Minecraft (Minecraft), but only the wrong version is present: 1.21.1!

**Comment by MrStickyPiston** [comment]
The mod is just for 1.21. im updating it

**Comment by flyover0112** [comment]
Thank you very much. Please comment here when finish the update, because Modrinth confused me, it says it is already for 1.21.1.

**Comment by MrStickyPiston** [comment]
Im having some troubles with loom during the update progress, it will take some time

**Comment by flyover0112** [comment]
No problem, do when you can, also if you may, can you make a jetpack that doesn't give penalties on mining when flying?

**Comment by MrStickyPiston** [comment]
fixed by #4
