### ISSUE TITLE
Unfortunately Still NOT WORKING with Sinytra Connector

### ISSUE THREAD

**Issue by flyover0112** [StickyPiston-development/BuildersJetpack#6]
Work on Fabric without problems, however, on Neoforge with Sinytra Connector is still not working. 
Is it possible to make a simple datapack of this mod so it doesn't have dependencies on the mod loader?
Thank you in advance.

**Comment by MrStickyPiston** [comment]
No, a datapack is not possible. Could you send logs?

**Comment by flyover0112** [comment]
Yes sure, logs are attached in this post. This is clean Neoforge 1.21.1 MC only with Sodium and Sodium Extra and Sinytra Connector, no other mods are installed. Jetpack requires a CONFIGURED mod, so I tried 1st use Fabric Version and it was not working, tried the Neoforge version, and only worked with 3.0.0. Configured, 3.1.0 was not working but still says that Jetpack has some errors and cannot load it. Here are the logs and thank you for the effort. Appreciate everything you do for this, I love your mod and love to use it on my MC. 
[latest.log](https://github.com/user-attachments/files/17389839/latest.log)
[debug.log](https://github.com/user-attachments/files/17389843/debug.log)
[crash-2024-10-16_13.45.57-fml.txt](https://github.com/user-attachments/files/17389848/crash-2024-10-16_13.45.57-fml.txt)

**Comment by MrStickyPiston** [comment]
The problem was builders jetpack was using an outdated api that was still in the fabric api but no longer in the forgified version. 

modrinth: https://modrinth.com/mod/builders-jetpack/version/1.4.7
