### ISSUE TITLE
Not craftable and only enchantable using table.

### ISSUE THREAD

**Issue by flyover0112** [StickyPiston-development/BuildersJetpack#7]
It works on Neoforge 1.21.1, but it is enchantable only in the vanilla enchanting table, and can't be enchanted by the book on anvil or with other enchant mods ( dark enchanting ). Also, JEI doesn't show a recipe for crafting in Neoforge.
It's not clear whether it needs a configuration mod or not. It works without one, but if you try to put the configuration in the mod folder, it only works with version 3.0.0, not with the latest 3.1.0.

Update: When I put ingredients to make fuel or jetpack, nothing comes out on crafting table. 
Can be only taken from creative and it works just fine but cannot be crafted.

Also tested on clean 1.21 Fabric, same situation, can't be crafted and JEI not show recipe.

Pictures are from clean Fabric 1.21

![2024-10-17_09 00 03](https://github.com/user-attachments/assets/f65d9f1a-b132-469e-b9ba-75d1ea1bbb96)
![2024-10-17_09 00 45](https://github.com/user-attachments/assets/1afd85b5-661b-4ac2-8d2f-5b67b5e324e1)

**Comment by MrStickyPiston** [comment]
Configuration 3.0.0 is included, versions above it crash

**Comment by flyover0112** [comment]
I come up with a simple solution until you make an update. I created 2 data packs with recipes for jetpack and fuel and added them to my world, now we can craft fuel and jetpack. 
Here are data packs if can be helpful.
Also if I understand correctly, there is no need to install a separate configuration mod it is already included inside of the main jetpack, right?
Everything else works fine, flying, refueling, and spending fuel, so the only problem now is crafting and enchanting.

[Jetpack.zip](https://github.com/user-attachments/files/17406697/Jetpack.zip)
[Fuel.zip](https://github.com/user-attachments/files/17406698/Fuel.zip)

**Comment by MrStickyPiston** [comment]
Fixed the crafting problem. Anvil enchanting seems to work fine for vanilla enchantments, so im closing this issue. If you experience that vanilla enchantments work but modded enchantments dont, make an compatibility issue. Although i dont think i will be fixing such issues on sinytra connector as it really hard to debug and test.

Modrinth: https://modrinth.com/mod/builders-jetpack/version/1.4.8

**Comment by MrStickyPiston** [comment]
Curseforge: https://www.curseforge.com/minecraft/mc-mods/builders-jetpack/files/5819608
